<?php

/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 */
require_once dirname(__DIR__) . '/vendor/autoload.php';
require_once dirname(__DIR__) . '/config/application.php';
/**
 * You need to add the JWT secret key to this file(and just before settings).
 */
defined('JWT_AUTH_SECRET_KEY') || define('JWT_AUTH_SECRET_KEY', '4vX*#K9q2!p@L7bZfS$');
defined('JWT_AUTH_CORS_ENABLE') || define('JWT_AUTH_CORS_ENABLE', true);
require_once ABSPATH . 'wp-settings.php';

